### ISSUE TITLE
Уточнения в инструкцию

### ISSUE THREAD

**Issue by dvauha** [RocketFox2409/MercuryESPHome#1]
Добрый день! Спасибо за отличную разработку.
Было бы здорово, если бы дополнили инструкцию с уклоном для тех, кто не очень силен в деталях.
В частности не очень понял схему подключения. Что еще нужно кроме счетчика и платы Wemos?
Спасибо. Успехов.

**Comment by RocketFox2409** [comment]
Здравствуйте, я работают над максимальным упрощением кода правда времени нету.
Для подключения требуется счетчик, RS485 to TTL конвертор и ESP8266

**Comment by vickkz** [comment]
драсте,судя по меркуриевскому мануалу 206 RN тоже должен работать, но чего то не хочет, показания не идут...рх и тх не моргает

**Comment by meta11st87** [comment]
Вы перестали работать над компонентом?

**Comment by meta11st87** [comment]
> драсте,судя по меркуриевскому мануалу 206 RN тоже должен работать, но чего то не хочет, показания не идут...рх и тх не моргает

У вас получилось победить 206ой меркурий? Какая у вас модификация оного? RN?

**Comment by vickkz** [comment]
> У вас получилось победить 206ой меркурий? Какая у вас модификация оного? RN?

пока не получилось, да версия RN,автор скинул мне модифкацию для 206,но чего то не пашет, мейби у меня косяк с подключением, хотя через юсб -рс485 стандартная меркуриевская утилита пашет

**Comment by DieMetRik** [comment]
В общем описываю свои эксперименты по дружбе Меркурия 206 и ESP+HA.

Первый сетап: Wemos D1 mini + RS485 (MAX485 chipset) + DC-DC конвертер для стабильного питания.
Подключение: 
D1 (GPIO5) --> TX (RO)
D2 (GPIO4) --> RX (DI)
D4 (GPIO2) --> DE+RE
3.3V --> VCC
GND --> GND

Работает, но очень не стабильно, постоянно отваливается Wemos.

Во втором сетапе добавил дополнительный DС-DC для питания модуля RS485
Стало постабильнее, но все равно отваливается, так как в Wemos использовал SoftwareSerial

Третий сетап аналогичен второму, только Wemos  заменил на ESP01s с HardwareSerial, работает стабильно. Больше трогать не буду. Отличие только:
GPIO0 -->DE+RE

Переписал немного код:
- Получение даты и частоты сети
- Проверка CRC полученного сообщения (иначе иногда данные искажаются)
- Добавил проверку данных на адекватность.
- Немного переделал отправку запросов и запись данных в РФ

Еще для платы на MAX требуется подавать сигнал высокого уровня, когда пишешь в RS485 и снимать когда читаешь. 

Если кому то нужно я попробую куда нить выложить.

**Comment by meta11st87** [comment]
> В общем описываю свои эксперименты по дружбе Меркурия 206 и ESP+HA.

> Еще для платы на MAX требуется подавать сигнал высокого уровня, когда пишешь в RS485 и снимать когда читаешь.
> 
> Если кому то нужно я попробую куда нить выложить.

Я был бы дико благодарен вам, если бы вы выложили схему, ссылки на модуля и код для совсем чайников. Сильно несилён в есп и вот этом вот всём. 

Могу спаять по схеме, и тыкнуть три кнопки на заливку прошивки((

**Comment by DieMetRik** [comment]
Сейчас подготовлю все...и выложу...

**Comment by DieMetRik** [comment]
В общем оформил все вот тут. https://github.com/DieMetRik/mercury_esphome/

**Comment by DrHooligun** [comment]
> > У вас получилось победить 206ой меркурий? Какая у вас модификация оного? RN?
> 
> пока не получилось, да версия RN,автор скинул мне модифкацию для 206,но чего то не пашет, мейби у меня косяк с подключением, хотя через юсб -рс485 стандартная меркуриевская утилита пашет

Доброго времени суток.
Победили Меркурий 206RN? Ситуация аналогична вашей, через usb2ttl стандартная утилита пашет.
Но как только пытаюсь выйти на удаленный съем показаний, ничего не работает. 
Пытался адаптировать прошивку DieMetRik на nodemcuv2 и на wemos, но ничего не выходит.

**Comment by vickkz** [comment]
> > > У вас получилось победить 206ой меркурий? Какая у вас модификация оного? RN?
> > 
> > 
> > пока не получилось, да версия RN,автор скинул мне модифкацию для 206,но чего то не пашет, мейби у меня косяк с подключением, хотя через юсб -рс485 стандартная меркуриевская утилита пашет
> 
> Доброго времени суток. Победили Меркурий 206RN? Ситуация аналогична вашей, через usb2ttl стандартная утилита пашет. Но как только пытаюсь выйти на удаленный съем показаний, ничего не работает. Пытался адаптировать прошивку DieMetRik на nodemcuv2 и на wemos, но ничего не выходит.

Да,завелась на DieMetRik прошивке там пофиксена авторизация, у меня изначально в скрипте при конвертации номера счётчика для авторизации добавлялся 0 или 02 не помню уже,и соответственно ни работало ничего,на последней прошивке всё работает,переустанавливал буквально неделю назад и всё завелась,а, ещё rx и tx в wemose от конвертера надо подключать согласно прошивке на d4 и d5 по моему,а не на rx tx

**Comment by DrHooligun** [comment]
> > > > У вас получилось победить 206ой меркурий? Какая у вас модификация оного? RN?
> > > 
> > > 
> > > пока не получилось, да версия RN,автор скинул мне модифкацию для 206,но чего то не пашет, мейби у меня косяк с подключением, хотя через юсб -рс485 стандартная меркуриевская утилита пашет
> > 
> > 
> > Доброго времени суток. Победили Меркурий 206RN? Ситуация аналогична вашей, через usb2ttl стандартная утилита пашет. Но как только пытаюсь выйти на удаленный съем показаний, ничего не работает. Пытался адаптировать прошивку DieMetRik на nodemcuv2 и на wemos, но ничего не выходит.
> 
> Да,завелась на DieMetRik прошивке там пофиксена авторизация, у меня изначально в скрипте при конвертации номера счётчика для авторизации добавлялся 0 или 02 не помню уже,и соответственно ни работало ничего,на последней прошивке всё работает,переустанавливал буквально неделю назад и всё завелась,а, ещё rx и tx в wemose от конвертера надо подключать согласно прошивке на d4 и d5 по моему,а не на rx tx

Низкий поклон Вам за разъяснение, все получилось. Благодарность и DieMetRik, безусловно.
