### ISSUE TITLE
Трёхфазные счётчики

### ISSUE THREAD

**Issue by booroondook-eng** [RocketFox2409/MercuryESPHome#2]
Ожидается ли версия для трёхфазных счётчиков (например, M230)?

**Comment by RocketFox2409** [comment]
Пытался делать, на руках его нету
Да и времени нету

**Comment by OM-3kChcBjgFR2COfP** [comment]
Ждём версию для 3х фазных счётчиков, а ещё лучше и с поддержкой CAN, так как таких счётчиков полно на вторичном рынке
